name: Daily Digest Bot

on:
  schedule:
    - cron: "30 6 * * *"   # 每天 06:30 UTC 运行
  workflow_dispatch:        # 手动触发

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run workflow-bot
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          EMAIL_FROM: ${{ secrets.EMAIL_FROM }}
          EMAIL_TO: ${{ secrets.EMAIL_TO }}
          EMAIL_SUBJECT_PREFIX: "[Daily Digest]"
          CALENDAR_ICS_URL: ${{ secrets.CALENDAR_ICS_URL }}
          GMAIL_SMTP_USER: ${{ secrets.GMAIL_SMTP_USER }}
          GMAIL_SMTP_APP_PASSWORD: ${{ secrets.GMAIL_SMTP_APP_PASSWORD }}
        run: python main.py