name: Daily Digest Bot

on:
  schedule:
    - cron: "30 6 * * *"   
  workflow_dispatch:       

permissions:
  contents: write 

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Write calendar credentials
        run: echo "${{ secrets.CREDENTIALS_CALENDAR_JSON }}" > credentials_calendar.json

      - name: Write gmail credentials
        run: echo "${{ secrets.CREDENTIALS_GMAIL_JSON }}" > credentials_gmail.json

      - name: Write calendar token
        run: echo '${{ secrets.TOKEN_CALENDAR_JSON }}' > token_calendar.json

      - name: Write gmail token
        run: echo '${{ secrets.TOKEN_GMAIL_JSON }}' > token_gmail.json

      - name: Run workflow-bot
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          EMAIL_FROM: ${{ secrets.EMAIL_FROM }}
          EMAIL_TO: ${{ secrets.EMAIL_TO }}
          EMAIL_SUBJECT_PREFIX: "[Daily Digest]"
        run: python main.py
      
      - name: Commit & Push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add -A
          if git diff --cached --quiet; then
            echo "No changes to commit."
          else
            git commit -m "chore: update daily digest ($(date -u +'%Y-%m-%d'))"
            git push
          fi