name: Daily ArXiv Digest

on:
  schedule:
    - cron: "*/5 * * * *"    # run daily at 07:00 UTC; adjust as needed
  workflow_dispatch: {}    # allow manual trigger

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          persist-credentials: true

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Export secrets
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          echo "OPENAI_API_KEY=${OPENAI_API_KEY}" >> $GITHUB_ENV
          # Optional custom model if you use a different one:
          # echo "OPENAI_MODEL=gpt-4o-mini" >> $GITHUB_ENV

      - name: Generate daily digest
        run: python generate_daily_digest.py

      - name: Commit & Push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add -A
          if git diff --cached --quiet; then
            echo "No changes to commit."
          else
            git commit -m "chore: update daily digest ($(date -u +'%Y-%m-%d %H:%M UTC'))"
            git push
          fi
  